name: Code Analysis

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  code_analysis:
    name: Code Analysis
    runs-on: ubuntu-22.04
    container:
      image: andrew2a1/cpp_analysis_tools

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run clang-format
        run: |
          clang-format-14 -i $(find libs -iname *.cpp) $(find libs -iname *.h)
          if [[ -n `git status --porcelain` ]]; then
            echo "::error ::Clang-format detected unformatted files!"
            git diff
            exit 1
          fi

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: /github/home/.conan2
          key: ${{ runner.os }}-clang-Release

      - name: Install Conan dependencies
        run: |
          conan install . \
            -pr:h=./conan/profiles/clang \
            -pr:b=./conan/profiles/clang \
            -s build_type=Release \
            -o yabil/*:with_tests=True \
            -o yabil/*:with_tbb=True \
            --build=missing

      - name: Configure
        run: |
          cmake --preset conan-release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=TRUE \
            -DCMAKE_VERBOSE_MAKEFILE=TRUE

      - name: Run Clang-tidy
        run: |
          find libs -iname "*.cpp" -not -path "*/ParallelStdImpl.cpp" -or -iname "*.h" -print0 \
            | parallel -0 clang-tidy -format-style=file -header-filter=.* -p build/Release {}

      - name: Run CppLint
        run: cpplint $(find libs -iname *.cpp) $(find libs -iname *.h)

      - name: Run CppCheck
        run: |
          cppcheck --project=build/Release/compile_commands.json \
            --enable=all --error-exitcode=1 --suppress=missingInclude:* --inline-suppr

      - name: Compile project
        working-directory: build/Release
        run: cmake --build . -j $(nproc) --config Release

      - name: Run tests
        working-directory: build/Release
        run: ctest -C Release --verbose -j "$(nproc)"
