name: Test on Linux (gcc 12.2)

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-22.04
    container:
      image: gcc:12.2

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.25.x"

      - name: Setup Python
        run: |
          apt-get update -y
          apt-get install python3-pip -y

      - name: Setup Valgrind
        run: apt-get install valgrind -y

      - name: Setup Conan
        run: python3 -m pip install conan

      - name: Make debug build
        run: python3 build.py --preset gcc --build_type Debug

      - name: Run tests
        working-directory: build/gcc_debug
        run: ctest --verbose -j "$(nproc)"

      - name: Run tests with Valgrind
        working-directory: build/gcc_debug
        run: |
          for test in $(find -iname *_tests); do
            valgrind -s --exit-on-first-error=yes --error-exitcode=1 \
              --leak-check=full --show-leak-kinds=all ./${test}
          done
