name: Build for Android (NDK r25c, clang 14.0.7)

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container:
      image: andrew2a1/cpp_android_tools

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup conan profile
        run: conan profile detect

      - name: Make release build
        run: python3 scripts/build.py --preset android --build_type Release
