name: Test on MacOS (apple-clang 14.0.3)

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: macos-13

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.25.x"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Conan
        run: |
          python -m pip install conan==2.2.3
          conan profile detect

      - name: Prepare build directory
        run: mkdir build

      - name: Install conan dependencies
        run: |
          conan install . \
            -pr:b=default \
            -pr:h=default \
            -s build_type=Debug \
            -o yabil/*:with_tests=True \
            -o yabil/*:with_tbb=True \
            -c yabil/*:tools.cmake.cmaketoolchain:generator=xcode \
            --build=missing

      - name: Configure
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app
          cmake --preset conan-debug -G "Xcode" -DCMAKE_COMPILE_WARNING_AS_ERROR=TRUE -DCMAKE_VERBOSE_MAKEFILE=TRUE

      - name: Build
        working-directory: build/Debug
        run: cmake --build . -j 4 --config Debug

      - name: Run tests
        working-directory: build/Debug
        run: ctest --verbose -j 4
