name: Test on MacOS (apple-clang 14.0.3)

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: macos-13

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.25.x"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Conan
        run: |
          python -m pip install conan==2.0.1
          conan profile detect

      - name: Prepare build directory
        run: mkdir build

      - name: Install conan dependencies
        run: conan install ./conan -pr:b=default -s build_type=Debug -of=build --build=missing

      - name: Configure
        working-directory: build
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app
          cmake .. -G "Xcode" \
            -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=FALSE \
            -DYABIL_ENABLE_TESTS=TRUE -DCMAKE_COMPILE_WARNING_AS_ERROR=TRUE

      - name: Build
        working-directory: build
        run: cmake --build . -j 4 --config Debug

      - name: Run tests
        working-directory: build
        run: ctest --verbose -j 4
