name: Test on Windows (MSVC)

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.4.1

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.25.x"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Conan
        run: python -m pip install conan

      - name: Prepare build directory
        run: mkdir build

      - name: Install conan dependencies
        working-directory: build
        run: conan install ../conan -pr:b=default -s build_type=Debug

      - name: Configure
        working-directory: build
        run: cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=FALSE -DYABIL_ENABLE_TESTS=TRUE

      - name: Build
        working-directory: build
        run: cmake --build . -j "${NUMBER_OF_PROCESSORS}" --config Debug

      - name: Run tests
        working-directory: build
        run: ctest --verbose -j "${NUMBER_OF_PROCESSORS}"
