name: Test on Windows (MSVC 17)

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.25.x"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Conan
        run: |
          python -m pip install conan==2.2.3
          conan profile detect

      - name: Prepare build directory
        run: mkdir build

      - name: Install conan dependencies
        run: |
          conan install . \
            -pr:b=default \
            -pr:h=default \
            -s build_type=Debug \
            -o yabil/*:with_tests=True \
            -o yabil/*:with_tbb=True \
            --build=missing

      - name: Configure
        run: cmake --preset conan-default -DCMAKE_COMPILE_WARNING_AS_ERROR=TRUE -DCMAKE_VERBOSE_MAKEFILE=TRUE

      - name: Build
        working-directory: build
        run: cmake --build . -j $(nproc) --config Debug

      - name: Run tests
        working-directory: build
        run: ctest --verbose -j $(nproc)
