name: Test on Windows (MSVC 17)

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.25.x"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Conan
        run: |
          python -m pip install conan==2.0.1
          conan profile detect

      - name: Prepare build directory
        run: mkdir build

      - name: Install conan dependencies
        working-directory: build
        run: conan install ../conan -pr:b=default -s build_type=Debug --build=missing

      - name: Configure
        working-directory: build
        run: cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=FALSE
          -DYABIL_ENABLE_TESTS=TRUE -DYABIL_ENABLE_TBB=TRUE -DCMAKE_COMPILE_WARNING_AS_ERROR=TRUE
          -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake

      - name: Build
        working-directory: build
        run: cmake --build . -j $(nproc) --config Debug

      - name: Run tests
        working-directory: build
        run: ctest --verbose -j $(nproc)
